### ISSUE TITLE
get panic on high RPS

### ISSUE THREAD

**Issue by JayChoi1736** [klaytn/klaytn-load-tester#5]
**Describe the bug**
get sigsegv and panic on high RPS 
`unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4119ea]`
it seems related to Go version(this issue have not been reproduced when we changed docker build base to go1.15) 

**To Reproduce**
1. build locust on docker and deploy by klaytn-deploy
2. run load-tester on high RPS ( ex. 5000 rps on transferValue)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by yoomee1313** [comment]
It is updated to go1.22 in new repo so I'll close this PR.
