### ISSUE TITLE
fix TCs based on dynamic fee mechanism

### ISSUE THREAD

**Issue by JayChoi1736** [klaytn/klaytn-load-tester#7]
**Describe the bug**
via klaytn release v1.9.0, most TCs do not work.

**Expected behavior**
remove failure caused by dynamic gas fee

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by hqjang-pepper** [comment]
Fixed at commit https://github.com/klaytn/klaytn-load-tester/commit/5ff104c8e5a2e40f30a4b889db5ba0662d9f8b6f
Need to fix in case of ServiceChain, too.
